LogESP/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views

from LogESP import views

urlpatterns = [
    path('', login_required(views.index), name='index'),
    path('license/', login_required(
        TemplateView.as_view(template_name='license.html')),
        name='license'),
    path('hwam/', include('hwam.urls')),
    path('risk/', include('risk.urls')),
    path('siem/', include('siem.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/password_change/',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    path('accounts/password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
    #path('accounts/password_change/done/', auth_views., name=''),
    path('admin/', admin.site.urls),
]

hwam/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'hwam'
urlpatterns = [
    path('', login_required(views.index), name='index'),
    path('help/', login_required(views.help_index), name='help_index'),
    path('ou/', login_required(views.OUIndexView.as_view()),
        name='ou_index'),
    path('hw/', login_required(views.HWIndexView.as_view()),
        name='hw_index'),
    path('sw/', login_required(views.SWIndexView.as_view()),
        name='sw_index'),
    path('hw/search/', login_required(views.HWSearchView.as_view()),
        name='hw_search'),
    path('sw/search/', login_required(views.SWSearchView.as_view()),
        name='sw_search'),
    path('ou/<int:pk>/', login_required(views.OUDetailView.as_view()),
        name='ou_detail'),
    path('hw/<int:pk>/', login_required(views.HWDetailView.as_view()),
        name='hw_detail'),
    path('sw/<int:pk>/', login_required(views.SWDetailView.as_view()),
        name='sw_detail'),
    path('ou/add/', login_required(views.OUCreateView.as_view()),
        name='ou_create'),
    path('hw/add/', login_required(views.HWCreateView.as_view()),
        name='hw_create'),
    path('sw/add/', login_required(views.SWCreateView.as_view()),
        name='sw_create'),
    path('ou/<int:pk>/update/', login_required(views.OUUpdateView.as_view()),
        name='ou_update'),
    path('hw/<int:pk>/update/', login_required(views.HWUpdateView.as_view()),
        name='hw_update'),
    path('sw/<int:pk>/update/', login_required(views.SWUpdateView.as_view()),
        name='sw_update'),
    path('ou/<int:pk>/delete/', login_required(
        views.OUDeleteView.as_view()), name='ou_delete'),
    path('hw/<int:pk>/delete/', login_required(
        views.HWDeleteView.as_view()), name='hw_delete'),
    path('sw/<int:pk>/delete/', login_required(
        views.SWDeleteView.as_view()), name='sw_delete'),
]

hwam/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, DeleteView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import PermissionRequiredMixin

from .models import OrganizationalUnit
from .models import HardwareAsset
from .models import SoftwareAsset

# Create your views here.

def index(request):
    return render(request, 'hwam/index.html')

def help_index(request):
    return render(request, 'hwam/help_index.html')

class OUIndexView(ListView):
    model = OrganizationalUnit
    template_name = 'hwam/ou_index.html'
    context_object_name = 'ou_list'
    permission_required = 'hwam.view_organizationalunit'

    def get_queryset(self):
        """Return a list of parent-less organizational units"""
        parents = OrganizationalUnit.objects.filter(parent_ou=None)
        return parents

class HWIndexView(ListView):
    model = HardwareAsset
    template_name = 'hwam/hw_index.html'
    context_object_name = 'hw_list'
    permission_required = 'hwam.view_hardwareasset'

    def get_queryset(self):
        """Return a list of parent-less hardware assets"""
        return HardwareAsset.objects.filter(
                parent_hardware=None).order_by('org_unit')

class HWSearchView(ListView):
    model = HardwareAsset
    template_name = "hwam/hw_search.html"
    context_object_name = 'hw_list'
    permission_required = 'hwam.view_hardwareasset'
    paginate_by = 20
    def get_queryset(self):
        filter_val = self.request.GET.get('filter')
        if filter_val and filter_val != '':
            new_context = HardwareAsset.objects.filter(
                name=filter_val,
            )
            return new_context
        else:
            return HardwareAsset.objects.all()
    def get_context_data(self, **kwargs):
        context = super(HWSearchView, self).get_context_data(**kwargs)
        context['filter'] = self.request.GET.get('filter', '')
        #context['orderby'] = self.request.GET.get('orderby', 'org_unit')
        return context

class SWIndexView(ListView):
    model = SoftwareAsset
    template_name = 'hwam/sw_index.html'
    context_object_name = 'sw_list'
    permission_required = 'hwam.view_softwareasset'

    def get_queryset(self):
        """Return a tuple of software assets"""
        p = SoftwareAsset.objects.exclude(
            parent_hardware=None).order_by('org_unit')
        c = SoftwareAsset.objects.filter(
            parent_hardware=None).order_by('org_unit')
        if len(p) + len(c) > 0:
            return (p, c)
        else:
            return None

class SWSearchView(ListView):
    model = SoftwareAsset
    template_name = "hwam/sw_search.html"
    context_object_name = 'sw_list'
    permission_required = 'hwam.view_softwareasset'
    paginate_by = 20
    def get_queryset(self):
        filter_val = self.request.GET.get('filter')
        if filter_val and filter_val != '':
            new_context = SoftwareAsset.objects.filter(
                name=filter_val,
            )
            return new_context
        else:
            return SoftwareAsset.objects.all()
    def get_context_data(self, **kwargs):
        context = super(SWSearchView, self).get_context_data(**kwargs)
        context['filter'] = self.request.GET.get('filter', '')
        return context

class OUDetailView(DetailView):
    model = OrganizationalUnit
    template_name = 'hwam/ou_detail.html'
    context_object_name = 'ou'
    permission_required = 'hwam.view_organizationalunit'

class HWDetailView(DetailView):
    model = HardwareAsset
    template_name = 'hwam/hw_detail.html'
    context_object_name = 'hw'
    permission_required = 'hwam.view_hardwareasset'

class SWDetailView(DetailView):
    model = SoftwareAsset
    template_name = 'hwam/sw_detail.html'
    context_object_name = 'sw'
    permission_required = 'hwam.view_softwareasset'

class OUCreateView(PermissionRequiredMixin, CreateView):
    model = OrganizationalUnit
    permission_required = 'hwam.add_organizationalunit'
    fields = ['name', 'desc', 'unit_contact', 'parent_ou']
    def get_success_url(self):
        return reverse_lazy('hwam:ou_detail', args=(self.object.id,))

class HWCreateView(PermissionRequiredMixin, CreateView):
    model = HardwareAsset
    permission_required = 'hwam.add_hardwareasset'
    fields = ['name', 'desc', 'org_unit',
            'asset_owner', 'asset_custodian',
            'parent_hardware',
            'hardware_type', 'property_id',
            'device_maker', 'device_model',
            'location', 'status',
            'date_added', 'date_eol',
            ]
    def get_success_url(self):
        return reverse_lazy('hwam:hw_detail', args=(self.object.id,))

class SWCreateView(PermissionRequiredMixin, CreateView):
    model = SoftwareAsset
    permission_required = 'hwam.add_softwareasset'
    fields = [
            'name', 'desc', 'org_unit',
            'custodian_swam', 'custodian_csm', 'custodian_vul',
            'parent_hardware', 'parent_software',
            'hostname', 'domain_name',
            'ip4_address_1', 'ip4_address_2',
            'ip4_address_3', 'ip4_address_4', 
            'ip4_address_5', 'ip4_address_6',
            'ip4_address_7', 'ip4_address_8', 
            'ip6_address_1', 'ip6_address_2',
            'ip6_address_3', 'ip6_address_4', 
            'ip6_address_5', 'ip6_address_6',
            'ip6_address_7', 'ip6_address_8', 
            'software_type', 'sw_property_id',
            'package_vendor', 'package_name', 'package_version',
            'status',
            'date_added', 'date_eol',
            ]
    def get_success_url(self):
        return reverse_lazy('hwam:sw_detail', args=(self.object.id,))

class OUUpdateView(PermissionRequiredMixin, UpdateView):
    model = OrganizationalUnit
    permission_required = 'hwam.change_organizationalunit'
    template_name = 'hwam/organizationalunit_update_form.html'
    fields = ['name', 'desc', 'unit_contact', 'parent_ou']
    def get_success_url(self):
        return reverse_lazy('hwam:ou_detail', args=(self.object.id,))

class HWUpdateView(PermissionRequiredMixin, UpdateView):
    model = HardwareAsset
    permission_required = 'hwam.change_hardwareasset'
    template_name = 'hwam/hardwareasset_update_form.html'
    fields = ['name', 'desc', 'org_unit',
            'asset_owner', 'asset_custodian',
            'parent_hardware',
            'hardware_type', 'property_id',
            'device_maker', 'device_model',
            'location', 'status',
            'date_added', 'date_eol',
            ]
    def get_success_url(self):
        return reverse_lazy('hwam:hw_detail', args=(self.object.id,))

class SWUpdateView(PermissionRequiredMixin, UpdateView):
    model = SoftwareAsset
    template_name = 'hwam/softwareasset_update_form.html'
    permission_required = 'hwam.change_softwareasset'
    fields = [
            'name', 'desc', 'org_unit',
            'custodian_swam', 'custodian_csm', 'custodian_vul',
            'parent_hardware', 'parent_software',
            'hostname', 'domain_name',
            'ip4_address_1', 'ip4_address_2',
            'ip4_address_3', 'ip4_address_4', 
            'ip4_address_5', 'ip4_address_6',
            'ip4_address_7', 'ip4_address_8', 
            'ip6_address_1', 'ip6_address_2',
            'ip6_address_3', 'ip6_address_4', 
            'ip6_address_5', 'ip6_address_6',
            'ip6_address_7', 'ip6_address_8', 
            'software_type', 'sw_property_id',
            'package_vendor', 'package_name', 'package_version',
            'status',
            'date_added', 'date_eol',
            ]
    def get_success_url(self):
        return reverse_lazy('hwam:sw_detail', args=(self.object.id,))

class OUDeleteView(PermissionRequiredMixin, DeleteView):
    model = OrganizationalUnit
    permission_required = 'hwam.delete_organizationalunit'
    template_name = 'hwam/ou_delete.html'
    context_object_name = 'ou'
    def get_success_url(self):
        return reverse('hwam:ou_index')

class HWDeleteView(PermissionRequiredMixin, DeleteView):
    model = HardwareAsset
    permission_required = 'hwam.delete_hardwareasset'
    template_name = 'hwam/hw_delete.html'
    context_object_name = 'hw'
    def get_success_url(self):
        return reverse('hwam:hw_index')

class SWDeleteView(PermissionRequiredMixin, DeleteView):
    model = SoftwareAsset
    permission_required = 'hwam.delete_softwareasset'
    template_name = 'hwam/sw_delete.html'
    context_object_name = 'sw'
    def get_success_url(self):
        return reverse('hwam:sw_index')

hwam/templates/hwam/hw_delete.html
{% extends "hwam/base.html" %}

{% block sub-title %}Delete Hardware Asset | {% endblock %}

{% block content-main %}

<h1>Delete Hardware Asset</h1>

<p>Are you sure you want to delete {{ hw }}?</p>

<form action="{% url 'hwam:hw_delete' hw.id %}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Delete" />
  <a href="{% url 'hwam:hw_detail' hw.id %}">Cancel</a>
</form>

{% endblock %}

hwam/templates/hwam/hw_detail.html
{% extends "hwam/base.html" %}

{% block sub-title %}Hardware Asset - {{ hw }} | {% endblock %}

{% block content-main %}

<h1>{{ hw }} (Hardware Asset)</h1>
<a href="{% url 'hwam:hw_update' hw.id %}">Edit</a>
&middot;
<a href="{% url 'hwam:hw_delete' hw.id %}">Delete</a>
&middot;
<a href="{% url 'hwam:hw_index' %}">Index</a>

<p>{{ hw.desc }}</p>
<ul>
    <li>Organizational Unit:
        <a href="{% url 'hwam:ou_detail' hw.org_unit.id %}">
            {{ hw.org_unit }}</a></li>
    <li>Owner:
        {% if hw.asset_owner %}
            {{ hw.asset_owner.username }}
            <a href="mailto:{{ hw.asset_owner.email }}">
                {{ hw.asset_owner.email }}</a>
        {% else %}
            {{ hw.org_unit.unit_contact.username }}
            <a href="mailto:{{ hw.org_unit.unit_contact.email }}">
                {{ hw.org_unit.unit_contact.email }}</a>
        {% endif %}
    </li>
    <li>Custodian:
        {% if hw.asset_custodian %}
            {{ hw.asset_custodian.username }}
            <a href="mailto:{{ hw.asset_custodian.email }}">
                {{ hw.asset_custodian.email }}</a>
        {% else %}
            {{ hw.org_unit.unit_contact.username }}
            <a href="mailto:{{ hw.org_unit.unit_contact.email }}">
                {{ hw.org_unit.unit_contact.email }}</a>
        {% endif %}
    </li>
    {% if hw.parent_hardware %}
    <li>Parent Hardware:<ul>
        <li><a href="{% url 'hwam:hw_detail' hw.parent_hardware.id %}">
                {{ hw.parent_hardware }}</a></li>
        </ul></li>
    {% endif %}
    {% if hw.child_hardware.all %}
        <li>Child Hardware:<ul>
            {% for a in hw.child_hardware.all %}
                <li><a href="{% url 'hwam:hw_detail' a.id %}">
                        {{ a }}</a></li>
            {% endfor %}
        </ul></li>
    {% endif %}
    {% if hw.child_software.all %}
        <li>Child Software:<ul>
            {% for a in hw.child_software.all %}
                <li><a href="{% url 'hwam:sw_detail' a.id %}">
                        {{ a }}</a></li>
            {% endfor %}
            </ul></li>
    {% endif %}
    <li>Hardware Type: {{ hw.hardware_type }}</li>
    <li>Property ID: {{ hw.property_id }}</li>
    <li>Device Maker: {{ hw.device_maker }}</li>
    <li>Device Model: {{ hw.device_model }}</li>
    <li>Location: {{ hw.location }}</li>
    <li>Status: {{ hw.status }}</li>
    <li>Lifespan:<ul>
    <li>Date Added: {{ hw.date_added }}</li>
    <li>EOL Date: {{ hw.date_eol }}</li></ul></li>
</ul>

{% endblock %}

hwam/templates/hwam/hw_index.html
{% extends "hwam/base.html" %}

{% block sub-title %}Hardware Assets | {% endblock %}

{% block content-main %}

<h1>Hardware Assets</h1>
<a href="{% url 'hwam:hw_create' %}">Add</a>
&middot;
<a href="{% url 'hwam:hw_search' %}">Search</a>

{% if hw_list %}
    <ul>
        {% for a in hw_list %}
            {% include "hwam/hw_tree_view.html" %}
        {% endfor %}
    </ul>
{% else %}
    <p>No assets.</p>
{% endif %}

{% endblock %}

hwam/templates/hwam/hw_search.html
{% extends "hwam/base.html" %}

{% block sub-title %}Hardware Asset Search | {% endblock %}

{% block content-main %}

<h1>Hardware Asset Search</h1>

<form method="get" action="{% url 'hwam:hw_search' %}">
    <p>Filter: <input type="text" value="{{filter}}" name="filter"/></p>
    <p><input type="submit" name="submit" value="Submit"/></p>
</form>

{% if hw_list %}
    {% for a in hw_list %}
        <ul>
            <li><a href="{% url 'hwam:hw_detail' a.id %}">{{ a }}</a></li>
        </ul>
    {% endfor %}
{% else %}
    <p>No assets.</p>
{% endif %}

{% endblock %}

hwam/templates/hwam/hw_tree_view.html
<li><a href="{% url 'hwam:hw_detail' a.id %}">{{ a.name }}</a>
    {% if a.child_hardware.all %}
        <ul>
            {% for c in a.child_hardware.all %}
                {% with a=c template_name="hwam/hw_tree_view.html" %}
                    {% include template_name %}
                {% endwith %}
            {% endfor %}
        </ul>
    {% endif %}
</li>

hwam/templates/hwam/index.html
{% extends "hwam/base.html" %}

{% block sub-title %}Index | {% endblock %}

{% block content-main %}

<h1>Asset Management</h1>

<ul>
    <li><a href="{% url 'hwam:ou_index' %}">Organizational Units</a></li>
    <li><a href="{% url 'hwam:hw_index' %}">Hardware Assets</a></li>
    <li><a href="{% url 'hwam:sw_index' %}">Software Assets</a></li>
</ul>

{% endblock %}

hwam/templates/hwam/navigation.html
<div id="topbar">
    <div class="navbar">
        <div class="navbar-content">
            <div class="navbar-left">
                <a class="navbar" href="{% url 'hwam:index' %}">
                    <b>Assets</b></a>
                &middot;
                <a class="navbar" href="{% url 'hwam:ou_index' %}">
                    Org. Units</a>
                &middot;
                <a class="navbar" href="{% url 'hwam:hw_index' %}">
                    Hardware Assets</a>
                &middot;
                <a class="navbar" href="{% url 'hwam:sw_index' %}">
                    Software Assets</a>
            </div>
            <div class="navbar-right">
                <a class="navbar" href="{% url 'hwam:help_index' %}">
                    Help</a>
            </div>
        </div>
    </div>
</div>

hwam/templates/hwam/organizationalunit_update_form.html
{% extends "hwam/base.html" %}

{% block sub-title %}Update Organizational Unit | {% endblock %}

{% block content-main %}

<h1>Update Organizational Unit</h1>
{% if form.errors %}
<p>There were some errors.</p>

<ul>
    {% for field in form %}
    {% if field.errors %}
    <li>{{ field.label_tag }}: {{ field.errors }}</li>
    {% endif %}
    {% endfor %}
</ul>

{% endif %}

<form action="" method="post">{% csrf_token %}
    <table>
        <tr>
            <th>Attribute</th><th>Setting</th><th class="left">Description</th>
        </tr>
        <tr>
            <td class="right">Name</td><td>{{ form.name }}</td><td>The organizational unit's name.</td>
        </tr>
        <tr>
            <td class="right">Desc</td><td>{{ form.desc }}</td><td>A description of the organizational unit.</td>
        </tr>
        <tr>
            <td class="right">Contact</td><td>{{ form.unit_contact }}</td><td>The contact person for this organizational unit.</td>
        </tr>
        <tr>
            <td class="right">Parent OU</td><td>{{ form.parent_ou }}</td><td>This organizational unit's parent OU.</td>
        </tr>
    </table>
    <input type="submit" value="Save" />
</form>

{% endblock %}

hwam/templates/hwam/ou_detail.html
{% extends "hwam/base.html" %}

{% block sub-title %}Organizational Unit - {{ ou }} | {% endblock %}

{% block content-main %}

<h1>{{ ou }} (Organizational Unit)</h1>
<a href="{% url 'hwam:ou_update' ou.id %}">Edit</a>
&middot;
<a href="{% url 'hwam:ou_delete' ou.id %}">Delete</a>
&middot;
<a href="{% url 'hwam:ou_index' %}">Index</a>

<p>{{ ou.desc }}</p>
<ul>
    <li>Contact: {{ ou.unit_contact.username }}
        <a href="mailto:{{ ou.unit_contact.email }}">
            {{ ou.unit_contact.email }}</a>
    </li>
    {% if ou.parent_ou %}
        <li>Parent OU:
            <a href="{% url 'hwam:ou_detail' ou.parent_ou.id %}">
                {{ ou.parent_ou }}</a></li>
    {% endif %}
    {% if ou.child_ous.all %}
        <li>Child OUs:<ul>
        {% for u in ou.children %}
            <li><a href="{% url 'hwam:ou_detail' u.id %}">
                {{ u }}</a></li>
        {% endfor %}
        </ul></li>
    {% endif %}
    <li>Hardware Assets:<ul>
        {% for a in ou.hardware_assets.all %}
            <li><a href="{% url 'hwam:hw_detail' a.id %}">
                    {{ a }}</a></li>
        {% endfor %}
        </ul></li>
    <li>Software Assets:<ul>
        {% for a in ou.software_assets.all %}
            <li><a href="{% url 'hwam:sw_detail' a.id %}">
                    {{ a }}</a></li>
        {% endfor %}
        </ul></li>
</ul>

{% endblock %}

hwam/templates/hwam/ou_index.html
{% extends "hwam/base.html" %}

{% block sub-title %}Organizational Units | {% endblock %}

{% block content-main %}

<h1>Organizational Units</h1>
<a href="{% url 'hwam:ou_create' %}">Add</a>

{% if ou_list %}
    <ul>
        {% for u in ou_list %}
            {% include "hwam/ou_tree_view.html" %}
        {% endfor %}
    </ul>
{% else %}
    <p>No organizational units.</p>
{% endif %}

{% endblock %}

hwam/templates/hwam/ou_tree_view.html
<li><a href="{% url 'hwam:ou_detail' u.id %}">{{ u }}</a>
    {% if u.child_ous.all %}
        <ul>
            {% for c in u.children %}
                {% with u=c template_name="hwam/ou_tree_view.html" %}
                    {% include template_name %}
                {% endwith %}
            {% endfor %}
        </ul>
    {% endif %}
</li>

hwam/templates/hwam/sw_delete.html
{% extends "hwam/base.html" %}

{% block sub-title %}Delete Software Asset | {% endblock %}

{% block content-main %}

<h1>Delete Software Asset</h1>

<p>Are you sure you want to delete {{ sw }}?</p>

<form action="{% url 'hwam:sw_delete' sw.id %}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Delete" />
  <a href="{% url 'hwam:sw_detail' sw.id %}">Cancel</a>
</form>

{% endblock %}

hwam/templates/hwam/sw_index.html
{% extends "hwam/base.html" %}

{% block sub-title %}Software Assets | {% endblock %}

{% block content-main %}

<h1>Software Assets</h1>
<a href="{% url 'hwam:sw_create' %}">Add</a>
&middot;
<a href="{% url 'hwam:sw_search' %}">Search</a>

{% if sw_list %}
    <ul>
        <li>Running on hardware:
        <ul>
            {% for a in sw_list.0 %}
                <li><a href="{% url 'hwam:sw_detail' a.id %}">
                        {{ a }}</a></li>
            {% endfor %}
        </ul></li>
    </ul>
    <ul>
        <li>Running on software:
        <ul>
            {% for a in sw_list.1 %}
                <li><a href="{% url 'hwam:sw_detail' a.id %}">
                        {{ a }}</a></li>
            {% endfor %}
        </ul></li>
    </ul>
{% else %}
    <p>No assets.</p>
{% endif %}

{% endblock %}

hwam/templates/hwam/sw_search.html
{% extends "hwam/base.html" %}

{% block sub-title %}Software Asset Search | {% endblock %}

{% block content-main %}

<h1>Software Asset Search</h1>

<form method="get" action="{% url 'hwam:sw_search' %}">
    <p>Filter: <input type="text" value="{{filter}}" name="filter"/></p>
    <p><input type="submit" name="submit" value="Submit"/></p>
</form>

{% if sw_list %}
    {% for a in sw_list %}
        <ul>
            <li><a href="{% url 'hwam:sw_detail' a.id %}">{{ a }}</a></li>
        </ul>
    {% endfor %}
{% else %}
    <p>No assets.</p>
{% endif %}

{% endblock %}